export const sketchConfig = {
  labels: {
    dialog: "画板",
    palette: "墨水颜色",
    customInk: "选择自定义颜色",
    downloadPng: "下载 PNG",
    copyPng: "复制 PNG 图片",
    copiedPng: "PNG 图片已复制",
    shape: "形状",
    backgroundMenu: "选择画布背景色",
    customBackground: "自定义背景色",
    ratioMenu: "选择画布比例",
    clearConfirm: "确认清空画布",
    clearQuestion: "清空全部内容？",
    cancel: "取消",
    clear: "清空",
    close: "关闭",
    undo: "撤销 (Command/Ctrl+Z)",
    redo: "重做 (Command/Ctrl+Shift+Z)",
    clearCanvas: "清空画布",
    expandSettings: "展开画布设置",
    collapseSettings: "收起画布设置",
    background: "画布背景色",
    ratio: "画布比例",
    moveControlsOutside: "操作区移到画布外",
    moveControlsInside: "操作区移回画布内",
    browserFullscreen: "浏览器全屏",
    exitBrowserFullscreen: "退出浏览器全屏",
    interfaceFullscreen: "界面全屏",
    exitInterfaceFullscreen: "退出界面全屏",
  },
  tools: [
    { id: "select", label: "选择并移动" },
    { id: "pen", label: "画笔" },
    { id: "text", label: "文字" },
    { id: "eraser", label: "橡皮擦" },
  ],
  inkColors: [
    { name: "白色", value: "#ffffff" }, { name: "灰色", value: "#6b7280" }, { name: "棕色", value: "#92400e" },
    { name: "红色", value: "#dc2626" }, { name: "橙色", value: "#f97316" }, { name: "黄色", value: "#f59e0b" },
    { name: "绿色", value: "#16a34a" }, { name: "蓝绿色", value: "#0d9488" }, { name: "青色", value: "#06b6d4" },
    { name: "蓝色", value: "#2563eb" }, { name: "靛蓝色", value: "#4f46e5" }, { name: "紫色", value: "#9333ea" }, { name: "粉色", value: "#db2777" },
  ],
  backgroundColors: [
    { name: "深色", value: "#171717" }, { name: "白色", value: "#ffffff" }, { name: "暖灰", value: "#ede9e1" },
    { name: "浅蓝", value: "#e8f0f7" }, { name: "浅粉", value: "#f6e9ed" },
  ],
  ratios: [
    { id: "1:1", label: "正方形", width: 1, height: 1 }, { id: "4:3", label: "标准横向", width: 4, height: 3 },
    { id: "16:9", label: "宽屏横向", width: 16, height: 9 }, { id: "3:4", label: "标准纵向", width: 3, height: 4 },
    { id: "9:16", label: "宽屏纵向", width: 9, height: 16 }, { id: "3:2", label: "照片横向", width: 3, height: 2 },
  ],
};
